// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygopchrmoshctzhzvzte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnb3BjaHJtb3NoY3R6aHp2enRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjY2NDAsImV4cCI6MjA4NjUwMjY0MH0.8hIUQVNsHnZptA_X3s_CrKP0sjiMYvcudm5e0f_4ylY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});