project_id = "ygopchrmoshctzhzvzte"

[functions.user-sync-api]
verify_jwt = false

[functions.check-csm-delegations]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.manage-google-calendar]
verify_jwt = false

[functions.fathom-webhook]
verify_jwt = false

[functions.manage-fathom]
verify_jwt = false

[functions.missed-onboarding-webhook]
verify_jwt = false

[functions.sme-ticket-webhook]
verify_jwt = false

[functions.send-scheduled-messages]
verify_jwt = false


[functions.upsert-user]
verify_jwt = false
