INSERT INTO achievement_badges (badge_key, badge_name, description, category, tier, icon_emoji, points_value, requirement_type, requirement_value, auto_award) VALUES
('welcome_aboard', 'Welcome Aboard', 'Logged in for the first time', 'onboarding', 'bronze', '👋', 10, 'first_login', '{}', true),
('first_lesson', 'First Lesson', 'Completed your first lesson', 'onboarding', 'bronze', '📖', 15, 'lessons_completed', '{"count": 1}', true),
('first_task', 'Task Tackler', 'Submitted your first task', 'onboarding', 'bronze', '✅', 15, 'tasks_submitted', '{"count": 1}', true),
('quiz_rookie', 'Quiz Rookie', 'Passed your first quiz', 'onboarding', 'bronze', '🎯', 20, 'quizzes_passed', '{"count": 1}', true),
('phase_pioneer', 'Phase Pioneer', 'Completed your first phase', 'learning', 'bronze', '🏁', 25, 'phases_completed', '{"count": 1}', true),
('halfway_hero', 'Halfway Hero', 'Completed 50% of a course', 'learning', 'silver', '⚡', 50, 'course_progress', '{"percent": 50}', true),
('course_conqueror', 'Course Conqueror', 'Completed an entire course', 'learning', 'gold', '🏆', 100, 'courses_completed', '{"count": 1}', true),
('quiz_master', 'Quiz Master', 'Scored 100% on a quiz', 'learning', 'gold', '🧠', 50, 'perfect_quiz_score', '{}', true),
('task_machine', 'Task Machine', 'Submitted 10 tasks', 'learning', 'silver', '⚙️', 40, 'tasks_submitted', '{"count": 10}', true),
('overachiever', 'Overachiever', 'Submitted 25 tasks', 'learning', 'gold', '🌟', 75, 'tasks_submitted', '{"count": 25}', true),
('knowledge_seeker', 'Knowledge Seeker', 'Completed 5 phases', 'learning', 'silver', '🔍', 60, 'phases_completed', '{"count": 5}', true),
('scholar', 'Scholar', 'Passed 5 quizzes', 'learning', 'silver', '🎓', 50, 'quizzes_passed', '{"count": 5}', true),
('first_post', 'First Post', 'Sent your first community message', 'community', 'bronze', '💬', 10, 'messages_sent', '{"count": 1}', true),
('conversation_starter', 'Conversation Starter', 'Sent 10 community messages', 'community', 'bronze', '🗣️', 20, 'messages_sent', '{"count": 10}', true),
('social_butterfly', 'Social Butterfly', 'Sent 50 community messages', 'community', 'silver', '🦋', 40, 'messages_sent', '{"count": 50}', true),
('reaction_king', 'Reaction King', 'Gave 25 reactions to messages', 'community', 'bronze', '👑', 15, 'reactions_given', '{"count": 25}', true),
('helpful_hand', 'Helpful Hand', 'Replied to 10 threads', 'community', 'silver', '🤝', 30, 'thread_replies', '{"count": 10}', true),
('community_champion', 'Community Champion', 'Sent 100 community messages', 'community', 'gold', '🏅', 75, 'messages_sent', '{"count": 100}', true),
('day_one', 'Day One', 'Logged in 2 days in a row', 'consistency', 'bronze', '🔥', 10, 'login_streak', '{"days": 2}', true),
('on_a_roll', 'On a Roll', 'Logged in 5 days in a row', 'consistency', 'bronze', '🎲', 20, 'login_streak', '{"days": 5}', true),
('week_warrior', 'Week Warrior', 'Logged in 7 days in a row', 'consistency', 'silver', '⚔️', 35, 'login_streak', '{"days": 7}', true),
('two_week_titan', 'Two Week Titan', 'Logged in 14 days in a row', 'consistency', 'silver', '🛡️', 50, 'login_streak', '{"days": 14}', true),
('monthly_master', 'Monthly Master', 'Logged in 30 days in a row', 'consistency', 'gold', '👑', 100, 'login_streak', '{"days": 30}', true),
('dedicated_learner', 'Dedicated Learner', 'Completed tasks on 5 different days', 'consistency', 'bronze', '📚', 25, 'active_days', '{"days": 5}', true),
('unstoppable', 'Unstoppable', 'Completed tasks on 20 different days', 'consistency', 'gold', '💪', 75, 'active_days', '{"days": 20}', true),
('speed_demon', 'Speed Demon', 'Completed a phase within 3 days of unlocking', 'special', 'gold', '⚡', 75, 'fast_phase_completion', '{"days": 3}', true),
('perfectionist', 'Perfectionist', 'Scored 100% on 3 different quizzes', 'special', 'gold', '💎', 100, 'perfect_quiz_score', '{"count": 3}', true),
('early_bird', 'Early Bird', 'Submitted a task before its due date', 'special', 'silver', '🐦', 30, 'early_submission', '{}', true),
('all_rounder', 'All-Rounder', 'Earned a badge in every category', 'special', 'gold', '🌈', 150, 'all_categories', '{}', true);